
power <- read.csv("~/J. Hopkins - Data Science/RFiles/exdata_data_household_power_consumption/household_power_consumption.txt", sep=";", stringsAsFactors = FALSE)
str(power)
library(lubridate)
power$Date <- dmy(power$Date)
library(dplyr)
df1 <- filter(power, Date == "2007-02-01")
df2 <- filter(power, Date == "2007-02-02")
df <- rbind(df1,df2)
str(df)
df$Global_active_power <- as.numeric(as.character(df$Global_active_power))
df$Sub_metering_1 <- as.double(as.character(df$Sub_metering_1))
df$Sub_metering_2 <- as.double(as.character(df$Sub_metering_2))
df$Sub_metering_3 <- as.double(as.character(df$Sub_metering_3))
df$Voltage <- as.double(as.character(df$Voltage))
df$Global_reactive_power <- as.double(as.character(df$Global_reactive_power))

df$DT <- paste(df$Date, df$Time, sep = " ")
df$DT <- as.POSIXct(df$DT)
hist(df$Global_active_power, col = "red", main = "Global Active Power", ylim = c(0,1200), xlab = "Global Active Power (kilowatts)")
setwd("~/J. Hopkins - Data Science/RFiles")
dev.copy(png, file = "plot1.png")
dev.off()
