
power <- read.csv("~/J. Hopkins - Data Science/RFiles/exdata_data_household_power_consumption/household_power_consumption.txt", sep=";", stringsAsFactors = FALSE)
str(power)
library(lubridate)
power$Date <- dmy(power$Date)
library(dplyr)
df1 <- filter(power, Date == "2007-02-01")
df2 <- filter(power, Date == "2007-02-02")
df <- rbind(df1,df2)
str(df)
df$Global_active_power <- as.numeric(as.character(df$Global_active_power))
df$Sub_metering_1 <- as.double(as.character(df$Sub_metering_1))
df$Sub_metering_2 <- as.double(as.character(df$Sub_metering_2))
df$Sub_metering_3 <- as.double(as.character(df$Sub_metering_3))
df$Voltage <- as.double(as.character(df$Voltage))
df$Global_reactive_power <- as.double(as.character(df$Global_reactive_power))

df$DT <- paste(df$Date, df$Time, sep = " ")
df$DT <- as.POSIXct(df$DT)

par(mfrow = c(2,2))
plot(df$DT, df$Global_active_power, type = "l", ylab = "Global Active Power (kilowatts)",xlab ="")
plot(df$DT, df$Voltage, type = "l", ylab = "Voltage", xlab ="")
plot(df$DT, a, type = "l", ylab = "Energy Sub Metering",ylim = c(0,40), xlab = "datetime")
par(new=T)
plot(df$DT, b, type = "l", ylab = "Energy Sub Metering", col = 'red', ylim = c(0,40), xlab = "")
par(new=T)
plot(df$DT, c, type = "l", ylab = "Energy Sub Metering", col = 'blue', ylim = c(0,40), xlab = "", cex = 0.15)
legend("topright", pch = "-", col = c("black", "red", "blue"), legend= c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),cex = .50)
plot(df$DT, df$Global_reactive_power, type = "l", ylab = "Global Reactive Power", xlab = "datetime")
dev.copy(png, file = "plot4.png")
dev.off()
